Mixture cure models (Weibull and log-normal)
paul-buerkner/brms pull request #1453
Opened 2023-02-07 05:19 UTC by yananlong

See [this issue](https://github.com/paul-buerkner/brms/issues/1452)

2023-02-07 08:12 UTC, paul-buerkner commented
Thank you! This looks like a very highy quality PR! I will go through it in the next couple of days.

2023-02-07 08:22 UTC, yananlong commented
Thanks for your prompt reply! I've actually found a couple of typos that have been fixed in a newer commit.

2023-02-07 16:08 UTC, paul-buerkner requested changes
Overall, high quality PR! I have just a few comments and suggestions. What is more, I think it would make sense to add info about the mixcure models in the brms_families vignette.

2023-02-07 16:08 UTC, paul-buerkner commented on R/posterior_epred.R
> +posterior_epred_mixcure_lognormal <- function(prep) {
Why is it not possible to compute the expected value for these families?

2023-02-07 16:08 UTC, paul-buerkner commented on R/stan-likelihood.R
> +stan_log_lik_mixcure_weibull <- function(bterms, resp = "", mix = "", ...) {
It seems like `reqn` should always be true given the stan code of this model. If true, should the code below be changed or simplified?

2023-02-07 16:08 UTC, paul-buerkner commented on inst/chunks/fun_mixcure_lognormal.stan
> +real mixcure_lognormal_lpdf(real y, real mu, real sigma, real inc) {
can you add some empty lines between function definitions in both stan files? And add a little more doc at the top?

2023-02-07 16:08 UTC, paul-buerkner commented on tests/local/setup_tests_local.R
> +library(mixcure)
Do we really need to load this package here?

2023-02-07 16:08 UTC, paul-buerkner commented on tests/local/tests.models-6.R
> +    loo_compare(fit1, fit1)
I suggest adding additional tests to see if loo results are in a sensible range. Also please add tests for the posterior_predict method here (and for posterior_epred if implemented).

2023-02-07 18:36 UTC, yananlong commented on .gitignore
> +.ipynb*
Sorry about that, I use jupyter lab for editing so I added that line to avoid adding the checkpoints files. Will fix this.

2023-02-07 18:37 UTC, yananlong commented on R/distributions.R
> +    if (lower.tail) {
The convention is to use 2 spaces for indentation, correct?

2023-02-07 19:05 UTC, paul-buerkner commented on R/distributions.R
> +    if (lower.tail) {
Yes but what about the if statements afterwards?

2024-01-28 20:00 UTC, paul-buerkner commented
@yananlong Is this PR still something you are working on?

2024-04-12 04:23 UTC, arnaudmgh commented
Hello @yananlong and @paul-buerkner, 

I started modeling Lymphoma survival data using brms with the Weibull family. However, my posterior predictive survival curve decreases more or less like an exponential decay, the data curve can start very step and flattens at some point (i.e. high hazard followed by short hazard). I added a formula for the shape parameter `bf(time | cens(censor) ~ ..., shape ~ 1)` but it does not help fit much better.

I suspect I could fit the data better with a cure model. Is it something ready to use in brms? Or, should I pull this branch and try to install it in R?

Any guidance would be much appreciated. 

Best
Arnaud

2024-09-20 07:18 UTC, paul-buerkner commented
I will close this PR for now due to inactivity but please feel free to reopen it when you should find the time to work on it again.

2024-09-20 07:18 UTC, closed without merging

2024-09-23 08:19 UTC, yananlong commented
Hi Paul and Arnaud,

Sorry I have shelved this project for now. I will probably return to it in November.